# Use an official Node.js runtime as the base image
FROM node:21

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install application dependencies
RUN npm install

# Copy your Node.js application code into the container (replace 'app.js' with your actual entry file)
COPY app.js .

# Expose the application port (replace '3000' with your desired port)
EXPOSE 3000

# Define the command to start your application
CMD ["npm", "start"]
